version: '3.7'
services:
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "4443:4443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
      - ./docker/production/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./htpasswd:/etc/nginx/auth/htpasswd:ro
    depends_on:
      - registry

  registry:
    image: registry:2.6
    restart: always
    volumes:
      - registry:/var/lib/registry

volumes:
  registry: