version: '3.7'
services:
  registry:
    image: registry:2.6
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    ports:
      - "5001:5000"
    volumes:
      - ./htpasswd:/auth/htpasswd
      - registry:/var/lib/registry

volumes:
  registry: